#!/bin/bash

# Runs many simulations and puts the output log files in run-many

if [ "$#" -ne 3 ]; then
    echo "Usage: run-many num_threads num_runs json_file"
    exit 1
fi

if ! [ -e run_logs ]; then
    mkdir run_logs
fi


numCells=$1
jsonFile=$3


for i in $(eval echo {1..$2}); do
    timeStamp=$(date +%Y-%m-%d_%H:%M)
    ./CellDiv $numCells $jsonFile | tee "run_logs/run"$i"_"$timeStamp"_out.log"
done
